// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SI_Admin.API.Data;

namespace SI_Admin.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Framework.DataTypes.Model.Base.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contacto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCorto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("RFC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Base.ClienteNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataBase")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDBControl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NegocioID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreNegocio")
                        .HasColumnType("TEXT");

                    b.Property<string>("PWD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puerto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDB")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClienteNegocios");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Infraestructura.Aplicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aplicaciones");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Infraestructura.AppMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AplicacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaseIcono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Componente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasPie")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasTipo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PadreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermisosEspeciales")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaNavegacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("PadreId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClienteActualizaciones");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacionApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteActualizacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("ClienteActualizacionId");

                    b.ToTable("ClienteActualizacionApps");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacionNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteActualizacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NegocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreNegocio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteActualizacionId");

                    b.ToTable("ClienteActualizacionNegocios");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.Licencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoTotalActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumNegociosTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumUsuariosTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaqueteInicialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("PaqueteInicialId");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.LicenciaApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LicenciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("LicenciaId");

                    b.ToTable("LicenciaApps");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaseIcono")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumNegocios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumUsuarios")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.PaqueteApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("PaqueteId");

                    b.ToTable("PaqueteApps");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Base.ClienteNegocio", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Base.Cliente", null)
                        .WithMany("Negocios")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Infraestructura.AppMenu", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Infraestructura.Aplicacion", null)
                        .WithMany("Menu")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.DataTypes.Model.Infraestructura.AppMenu", "Padre")
                        .WithMany()
                        .HasForeignKey("PadreId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacion", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Base.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacionApp", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Infraestructura.Aplicacion", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacion", null)
                        .WithMany("Apps")
                        .HasForeignKey("ClienteActualizacionId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacionNegocio", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Licenciamiento.ClienteActualizacion", null)
                        .WithMany("Negocios")
                        .HasForeignKey("ClienteActualizacionId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.Licencia", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Base.Cliente", null)
                        .WithOne("Licencia")
                        .HasForeignKey("Framework.DataTypes.Model.Licenciamiento.Licencia", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.DataTypes.Model.Licenciamiento.Paquete", "PaqueteInicial")
                        .WithMany()
                        .HasForeignKey("PaqueteInicialId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.LicenciaApp", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Infraestructura.Aplicacion", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.DataTypes.Model.Licenciamiento.Licencia", null)
                        .WithMany("Apps")
                        .HasForeignKey("LicenciaId");
                });

            modelBuilder.Entity("Framework.DataTypes.Model.Licenciamiento.PaqueteApp", b =>
                {
                    b.HasOne("Framework.DataTypes.Model.Infraestructura.Aplicacion", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.DataTypes.Model.Licenciamiento.Paquete", null)
                        .WithMany("Apps")
                        .HasForeignKey("PaqueteId");
                });
#pragma warning restore 612, 618
        }
    }
}
